version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 99
    rebase-strategy: auto
    schedule:
      interval: weekly
      day: saturday
      time: "08:00"
      timezone: Europe/London
    target-branch: main
    assignees:
      - ascopes
