name: Build

on:
  push:
    branches: [main]
  schedule:
    # Run every 24 hours at 43 minutes past midnight.
    - cron: "43 0 * * *"
  workflow_dispatch: {}

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Validate shell scripts
        uses: ludeeus/action-shellcheck@master
        with:
          check_together: 'yes'
          scandir: .

  build:
    name: Build and Publish Blocklist
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      id-token: write
      pages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Compile blocklist
        run: ./build.sh

      - name: Upload blocklist to GitHub as a site
        uses: actions/upload-pages-artifact@v4
        with:
          path: out/

      - name: Deploy site to GitHub Pages
        uses: actions/deploy-pages@v4

      # If the deployment failed due to an internal error (e.g. an outage on GitHub),
      # then we may get stuck in a state where we are unable to rerun this step. This
      # happens because we create duplicate artifact uploads and the upload artifact
      # action mishandles duplicates. The easiest way around this is to just purge the
      # artifact if we failed so that any rerun can succeed.
      - name: Remove GitHub Pages artifacts
        uses: geekyeggo/delete-artifact@v5
        if: always()
        with:
          name: github-pages
          failOnError: false
